require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
    - 'spec/support/**/*'
    - 'tmp/**/*'
    - 'lib/swagger_client.rb'
    - 'lib/swagger_client/**/*'
    - 'spec/lib/swagger_client/**/*'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/IfUnlessModifier:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/ClassLength:
  Exclude:
    - 'app/services/orcid_api/query.rb'
Metrics/LineLength:
  Exclude:
    - 'spec/services/orcid_api/query_spec.rb'
