require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/IfUnlessModifier:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
