=begin
#ORCID Member

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: Latest

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::AffiliationGroupV30MembershipSummaryV30
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AffiliationGroupV30MembershipSummaryV30' do
  before do
    # run before each test
    @instance = SwaggerClient::AffiliationGroupV30MembershipSummaryV30.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AffiliationGroupV30MembershipSummaryV30' do
    it 'should create an instance of AffiliationGroupV30MembershipSummaryV30' do
      expect(@instance).to be_instance_of(SwaggerClient::AffiliationGroupV30MembershipSummaryV30)
    end
  end
  describe 'test attribute "last_modified_date"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "external_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "summaries"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
