=begin
#ORCID Member

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: Latest

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::BulkElement
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BulkElement' do
  before do
    # run before each test
    @instance = SwaggerClient::BulkElement.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BulkElement' do
    it 'should create an instance of BulkElement' do
      expect(@instance).to be_instance_of(SwaggerClient::BulkElement)
    end
  end
end
