=begin
#ORCID Member

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: Latest

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::LastModifiedDateV30
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LastModifiedDateV30' do
  before do
    # run before each test
    @instance = SwaggerClient::LastModifiedDateV30.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LastModifiedDateV30' do
    it 'should create an instance of LastModifiedDateV30' do
      expect(@instance).to be_instance_of(SwaggerClient::LastModifiedDateV30)
    end
  end
  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
