=begin
#ORCID Member

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: Latest

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ResearchResourceTitleV30
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ResearchResourceTitleV30' do
  before do
    # run before each test
    @instance = SwaggerClient::ResearchResourceTitleV30.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ResearchResourceTitleV30' do
    it 'should create an instance of ResearchResourceTitleV30' do
      expect(@instance).to be_instance_of(SwaggerClient::ResearchResourceTitleV30)
    end
  end
  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "translated_title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
