defaults: &defaults
  token: <%= ENV["TOKEN"] %>
  token_base_url: "orcid.org"
  api_base_url: "pub.orcid.org"
  api_version: "3.0"
test:
  <<: *defaults
  token: "test_token"
development:
  <<: *defaults
production:
  <<: *defaults
  api_base_url: "api.orcid.org"
staging:
  <<: *defaults
